In [1]:
import re

In [2]:
with open('./train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [3]:
len(text)

205

In [4]:
num_characters = 34  # 33 буквы + пробел

In [5]:
import keras
from keras.preprocessing.text import Tokenizer

In [6]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [7]:
tokenizer.fit_on_texts(text)

In [8]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [9]:
inp_chars = 6
data = tokenizer.texts_to_matrix(text)

In [10]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
n = data.shape[0]-inp_chars
n

199

In [12]:
import numpy as np

In [13]:
X = np.array([data[i : i + inp_chars, :] for i in range(n)])
Y = data[inp_chars:]  # предсказание следующего символа

In [14]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [15]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
from keras.layers import *
from keras.models import Sequential

In [17]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation="tanh"))
model.add(Dense(num_characters, activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284,534
Trainable params: 284,534
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss="categorical_crossentropy", metrics=["accuracy"], optimizer="adam")
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100


7/7 [==============================] - 2s 14ms/step - loss: 3.3796 - accuracy: 0.1005
Epoch 2/100
7/7 [==============================] - 0s 13ms/step - loss: 2.3578 - accuracy: 0.3719
Epoch 3/100
7/7 [==============================] - 0s 13ms/step - loss: 1.8995 - accuracy: 0.4573
Epoch 4/100
7/7 [==============================] - 0s 13ms/step - loss: 1.5164 - accuracy: 0.5377
Epoch 5/100
7/7 [==============================] - 0s 13ms/step - loss: 1.2683 - accuracy: 0.6231
Epoch 6/100
7/7 [==============================] - 0s 13ms/step - loss: 1.0246 - accuracy: 0.7437
Epoch 7/100
7/7 [==============================] - 0s 13ms/step - loss: 0.8763 - accuracy: 0.7739
Epoch 8/100
7/7 [==============================] - 0s 13ms/step - loss: 0.7758 - accuracy: 0.8040
Epoch 9/100
7/7 [==============================] - 0s 13ms/step - loss: 0.7016 - accuracy: 0.8442
Epoch 10/100
7/7 [==============================] - 0s 12ms/step - loss: 0.6886 - accuracy: 0.8141
Epoch 11/100
7/7 [=============

In [19]:
def buildPhrase(inp_str, str_len = 50):
    for i in range(str_len):
        x = []
        for j in range(i, i+inp_chars):
            x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

        x = np.array(x)
        inp = x.reshape(1, inp_chars, num_characters)

        pred = model.predict( inp ) # предсказываем OHE четвертого символа
        d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

        inp_str += d # дописываем строку

    return inp_str

In [20]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 23ms/step
утренноитввд са гяослотс  о теле ьнаоилобл  в коиедыеьни


## Слова

In [23]:
with open("./train_data.txt", "r", encoding="utf-8") as f:
    texts = f.read()
    texts = text.replace("\ufeff", "")  # убираем первый невидимый символ
texts

'Вы — лучший ответ на проблемы, которые возникли в понедельник.\nДумайте позитивно и верьте в свою способность достигать отличных результатов.\nЕсли вы смогли в понедельник подняться с постели, значит вы супер герой.'

In [26]:
maxWordsCount = 1000
tokenizer = Tokenizer(
    num_words=maxWordsCount,
    filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
    lower=True,
    split=" ",
    char_level=False,
)
tokenizer.fit_on_texts([texts])
# tokenizer.index_word

In [28]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [31]:
data = tokenizer.texts_to_sequences([texts])
data

[[1,
  4,
  5,
  6,
  7,
  8,
  9,
  2,
  3,
  10,
  11,
  12,
  13,
  2,
  14,
  15,
  16,
  17,
  18,
  19,
  1,
  20,
  2,
  3,
  21,
  22,
  23,
  24,
  1,
  25,
  26]]

In [33]:
len(data[0])

31

In [32]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print(res.shape)

(31, 1000)


In [34]:
inp_words = 3
n = res.shape[0] - inp_words

In [35]:
X = np.array([res[i : i + inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [36]:
model = Sequential()
model.add(Input((inp_words, maxWordsCount)))
model.add(SimpleRNN(128, activation="tanh"))
model.add(Dense(maxWordsCount, activation="softmax"))
model.summary()

model.compile(loss="categorical_crossentropy", metrics=["accuracy"], optimizer="adam")

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 128)               144512    
                                                                 
 dense_1 (Dense)             (None, 1000)              129000    
                                                                 
Total params: 273,512
Trainable params: 273,512
Non-trainable params: 0
_________________________________________________________________


In [38]:
history = model.fit(X, Y, batch_size=32, epochs=19)

Epoch 1/19
1/1 [==============================] - 0s 13ms/step - loss: 2.3577 - accuracy: 0.4643
Epoch 2/19
1/1 [==============================] - 0s 12ms/step - loss: 2.3077 - accuracy: 0.4643
Epoch 3/19
1/1 [==============================] - 0s 11ms/step - loss: 2.2546 - accuracy: 0.5357
Epoch 4/19
1/1 [==============================] - 0s 12ms/step - loss: 2.1987 - accuracy: 0.5714
Epoch 5/19
1/1 [==============================] - 0s 13ms/step - loss: 2.1404 - accuracy: 0.6071
Epoch 6/19
1/1 [==============================] - 0s 12ms/step - loss: 2.0798 - accuracy: 0.6786
Epoch 7/19
1/1 [==============================] - 0s 13ms/step - loss: 2.0177 - accuracy: 0.7500
Epoch 8/19
1/1 [==============================] - 0s 16ms/step - loss: 1.9544 - accuracy: 0.8214
Epoch 9/19
1/1 [==============================] - 0s 13ms/step - loss: 1.8906 - accuracy: 0.8214
Epoch 10/19
1/1 [==============================] - 0s 12ms/step - loss: 1.8268 - accuracy: 0.8214
Epoch 11/19
1/1 [============

In [41]:
def buildPhrase(texts, str_len = 20):
    res = texts
    data = tokenizer.texts_to_sequences([texts])[0]
    for i in range(str_len):
        x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
        inp = x.reshape(1, inp_words, maxWordsCount)

        pred = model.predict( inp ) # предсказываем OHE четвертого символа
        indx = pred.argmax(axis=1)[0]
        data.append(indx)

        res += f" {tokenizer.index_word[indx]}"  # дописываем строку

    return res

In [42]:
res = buildPhrase("позитив добавляет годы")
print(res)

ValueError: cannot reshape array of size 0 into shape (1,3,1000)